# Tensors

In [1]:
import torch
print(torch.__version__)

2.6.0+cpu


In [2]:
device = "gpu" if torch.cuda.is_available() else "cpu"

## Creating Tensors

### Creating tensor using empty: it allocate memory and displays the value that exist in that memory already

In [3]:
t = torch.empty(2,3)

In [4]:
type(t)

torch.Tensor

In [5]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.rand(2,3)

tensor([[0.7962, 0.6669, 0.9868],
        [0.3753, 0.6192, 0.8051]])

In [8]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [9]:
torch.tensor([1,2,3,4,5])

tensor([1, 2, 3, 4, 5])

In [10]:
torch.arange(0,15,3)

tensor([ 0,  3,  6,  9, 12])

In [11]:
torch.linspace(1,10,10)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [12]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [13]:
torch.full((3,2),5.2)

tensor([[5.2000, 5.2000],
        [5.2000, 5.2000],
        [5.2000, 5.2000]])

## Tensor Shapes

In [14]:
x = torch.tensor([[1,2,3], [4,5,6]])

In [15]:
x.shape

torch.Size([2, 3])

In [16]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [19]:
torch.rand_like(x, dtype=torch.float)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

## Tensor Data Types

In [20]:
x.dtype

torch.int64

In [21]:
torch.tensor([1.0, 2.0, 3.0], dtype =torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [22]:
torch.tensor([1.0, 2.0, 3.0], dtype =torch.float32)

tensor([1., 2., 3.])

In [23]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## Mathematical Operations

In [24]:
x = torch.randn(2,2)
x

tensor([[ 2.2082, -0.6380],
        [ 0.4617,  0.2674]])

In [25]:
print(x + 2)
print(x-2)
print(x*2)
print(x/2)
print(x//2)
print(x%2)
print(x**2)

tensor([[4.2082, 1.3620],
        [2.4617, 2.2674]])
tensor([[ 0.2082, -2.6380],
        [-1.5383, -1.7326]])
tensor([[ 4.4164, -1.2760],
        [ 0.9233,  0.5347]])
tensor([[ 1.1041, -0.3190],
        [ 0.2308,  0.1337]])
tensor([[ 1., -1.],
        [ 0.,  0.]])
tensor([[0.2082, 1.3620],
        [0.4617, 0.2674]])
tensor([[4.8762, 0.4070],
        [0.2131, 0.0715]])


In [26]:
first = torch.randint(1,10, (2,2))
second = torch.randint(1,10, (2,2))
first, second

(tensor([[5, 9],
         [2, 6]]),
 tensor([[9, 5],
         [3, 1]]))

In [27]:
print(first + second)
print(first - second)
print(first * second)
print(first // second)
print(first % second)
print(first ** second)

tensor([[14, 14],
        [ 5,  7]])
tensor([[-4,  4],
        [-1,  5]])
tensor([[45, 45],
        [ 6,  6]])
tensor([[0, 1],
        [0, 6]])
tensor([[5, 4],
        [2, 0]])
tensor([[1953125,   59049],
        [      8,       6]])


In [28]:
c = torch.randint(1,10, (1,10)) * -1
c

tensor([[-2, -2, -4, -4, -8, -8, -9, -8, -3, -6]])

In [29]:
torch.abs(c)

tensor([[2, 2, 4, 4, 8, 8, 9, 8, 3, 6]])

In [30]:
torch.neg(c)

tensor([[2, 2, 4, 4, 8, 8, 9, 8, 3, 6]])

In [31]:
torch.round(x)

tensor([[ 2., -1.],
        [ 0.,  0.]])

In [32]:
torch.ceil(x)

tensor([[3., -0.],
        [1., 1.]])

In [33]:
torch.floor(x)

tensor([[ 2., -1.],
        [ 0.,  0.]])

In [34]:
torch.clamp(first, 3, 5)

tensor([[5, 5],
        [3, 5]])

## Reduction Operation

In [35]:
torch.sum(first)

tensor(22)

In [36]:
torch.sum(first, dim=0)

tensor([ 7, 15])

In [37]:
torch.sum(first, dim=1)

tensor([14,  8])

In [38]:
torch.mean(x) # can also do for dimensions

tensor(0.5748)

In [39]:
torch.median(first)

tensor(5)

In [40]:
torch.min(first)

tensor(2)

In [41]:
torch.max(first)

tensor(9)

In [42]:
torch.prod(first)

tensor(540)

In [43]:
torch.std(x)

tensor(1.1897)

In [44]:
torch.var(x)

tensor(1.4154)

In [45]:
torch.argmax(first)

tensor(1)

In [46]:
torch.argmin(first)

tensor(2)

## Matrix Operations

In [47]:
torch.matmul(first, second)

tensor([[72, 34],
        [36, 16]])

In [48]:
v1 = torch.tensor([1,2,3])
v2 = torch.tensor([4,5,6])

In [49]:
torch.dot(v1, v2)

tensor(32)

In [50]:
torch.transpose(first, 0, 1)

tensor([[5, 2],
        [9, 6]])

In [51]:
torch.det(x)

tensor(0.8849)

In [52]:
torch.inverse(x)

tensor([[ 0.3021,  0.7210],
        [-0.5217,  2.4954]])

## Comparison Operation

In [53]:
first > second ## so on and os forth for each operation

tensor([[False,  True],
        [False,  True]])

## Special Funtion


In [54]:
torch.log(first)

tensor([[1.6094, 2.1972],
        [0.6931, 1.7918]])

In [55]:
torch.exp(first)

tensor([[1.4841e+02, 8.1031e+03],
        [7.3891e+00, 4.0343e+02]])

In [56]:
torch.sqrt(first)

tensor([[2.2361, 3.0000],
        [1.4142, 2.4495]])

In [57]:
torch.sigmoid(first)

tensor([[0.9933, 0.9999],
        [0.8808, 0.9975]])

In [58]:
torch.softmax(x, dim=1)

tensor([[0.9451, 0.0549],
        [0.5484, 0.4516]])

In [59]:
torch.relu(c)

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

## Inplace Operations

In [60]:
## new tensor is created after the operation and occupy memory. so instead of using seperate we save it on the existing

In [61]:
first.add(second)

tensor([[14, 14],
        [ 5,  7]])

In [62]:
c.relu_() # underscore is used for inplace

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

## Copying a Tensor

In [63]:
# a = b if one changes the other changes
third = torch.clone(first)

## Tensor Operations on GPU

In [64]:
device = "gpu" if torch.cuda.is_available() else "cpu"


In [65]:
first.to(device)

tensor([[5, 9],
        [2, 6]])

## Reshaping Tensor

In [66]:
for_reshape = torch.rand(3,4)
for_reshape

tensor([[0.5547, 0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890, 0.2814],
        [0.7886, 0.5895, 0.7539, 0.1952]])

In [67]:
torch.reshape(for_reshape, (6,2))

tensor([[0.5547, 0.3423],
        [0.6343, 0.3644],
        [0.7104, 0.9464],
        [0.7890, 0.2814],
        [0.7886, 0.5895],
        [0.7539, 0.1952]])

In [68]:
torch.flatten(for_reshape)

tensor([0.5547, 0.3423, 0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886,
        0.5895, 0.7539, 0.1952])

In [69]:
torch.permute(for_reshape, (1, 0))

tensor([[0.5547, 0.7104, 0.7886],
        [0.3423, 0.9464, 0.5895],
        [0.6343, 0.7890, 0.7539],
        [0.3644, 0.2814, 0.1952]])

In [70]:
img = torch.randn(226, 226,3)

In [71]:
img.unsqueeze(3).shape

torch.Size([226, 226, 3, 1])

In [72]:
torch.squeeze(for_reshape, 1)

tensor([[0.5547, 0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890, 0.2814],
        [0.7886, 0.5895, 0.7539, 0.1952]])

## Numpy and PyTorch

In [73]:
first = first.numpy()

In [74]:
type(first)

numpy.ndarray

In [75]:
first = torch.from_numpy(first)

In [76]:
type(first)

torch.Tensor