In [ ]:
import torch
print(torch.__version__)

In [ ]:
device = "gpu" if torch.cuda.is_available() else "cpu"

## Creating Tensors

### Creating tensor using empty: it allocate memory and displays the value that exist in that memory already

In [ ]:
t = torch.empty(2,3)

In [ ]:
type(t)

In [ ]:
torch.zeros(2,3)

In [ ]:
torch.ones(2,3)

In [ ]:
torch.rand(2,3)

In [ ]:
torch.manual_seed(42)
torch.rand(2,3)

In [ ]:
torch.tensor([1,2,3,4,5])

In [ ]:
torch.arange(0,15,3)

In [ ]:
torch.linspace(1,10,10)

In [ ]:
torch.eye(3)

In [ ]:
torch.full((3,2),5.2)

## Tensor Shapes

In [ ]:
x = torch.tensor([[1,2,3], [4,5,6]])

In [ ]:
x.shape

In [ ]:
torch.empty_like(x)

In [ ]:
torch.zeros_like(x)

In [ ]:
torch.ones_like(x)

In [ ]:
torch.rand_like(x, dtype=torch.float)

## Tensor Data Types

In [ ]:
x.dtype

In [ ]:
torch.tensor([1.0, 2.0, 3.0], dtype =torch.int32)

In [ ]:
torch.tensor([1.0, 2.0, 3.0], dtype =torch.float32)

In [ ]:
x.to(torch.float32)

## Mathematical Operations

In [ ]:
x = torch.randn(2,2)
x

In [ ]:
print(x + 2)
print(x-2)
print(x*2)
print(x/2)
print(x//2)
print(x%2)
print(x**2)

In [ ]:
first = torch.randint(1,10, (2,2))
second = torch.randint(1,10, (2,2))
first, second

In [ ]:
print(first + second)
print(first - second)
print(first * second)
print(first // second)
print(first % second)
print(first ** second)

In [ ]:
c = torch.randint(1,10, (1,10)) * -1
c

In [ ]:
torch.abs(c)

In [ ]:
torch.neg(c)

In [ ]:
torch.round(x)

In [ ]:
torch.ceil(x)

In [ ]:
torch.floor(x)

In [ ]:
torch.clamp(first, 3, 5)

## Reduction Operation

In [ ]:
torch.sum(first)

In [ ]:
torch.sum(first, dim=0)

In [ ]:
torch.sum(first, dim=1)

In [ ]:
torch.mean(x) # can also do for dimensions

In [ ]:
torch.median(first)

In [ ]:
torch.min(first)

In [ ]:
torch.max(first)

In [ ]:
torch.prod(first)

In [ ]:
torch.std(x)

In [ ]:
torch.var(x)

In [ ]:
torch.argmax(first)

In [ ]:
torch.argmin(first)

## Matrix Operations

In [ ]:
torch.matmul(first, second)

In [ ]:
v1 = torch.tensor([1,2,3])
v2 = torch.tensor([4,5,6])

In [ ]:
torch.dot(v1, v2)

In [ ]:
torch.transpose(first, 0, 1)

In [ ]:
torch.det(x)

In [ ]:
torch.inverse(x)

## Comparison Operation

In [ ]:
first > second ## so on and os forth for each operation

## Special Funtion


In [ ]:
torch.log(first)

In [ ]:
torch.exp(first)

In [ ]:
torch.sqrt(first)

In [ ]:
torch.sigmoid(first)

In [ ]:
torch.softmax(x, dim=1)

In [ ]:
torch.relu(c)

## Inplace Operations

In [ ]:
## new tensor is created after the operation and occupy memory. so instead of using seperate we save it on the existing

In [ ]:
first.add(second)

In [ ]:
c.relu_() # underscore is used for inplace

In [ ]:
c

## Copying a Tensor

In [ ]:
# a = b if one changes the other changes
third = torch.clone(first)

## Tensor Operations on GPU

In [ ]:
device = "gpu" if torch.cuda.is_available() else "cpu"


In [ ]:
first.to(device)

## Reshaping Tensor

In [172]:
for_reshape = torch.rand(3,4)
for_reshape

tensor([[0.6273, 0.7358, 0.4368, 0.3023],
        [0.7786, 0.1018, 0.8160, 0.3060],
        [0.5077, 0.4012, 0.5606, 0.3489]])

In [ ]:
torch.reshape(for_reshape, (6,2))

In [ ]:
torch.flatten(for_reshape)

In [174]:
torch.permute(for_reshape, (1, 0))

tensor([[0.6273, 0.7786, 0.5077],
        [0.7358, 0.1018, 0.4012],
        [0.4368, 0.8160, 0.5606],
        [0.3023, 0.3060, 0.3489]])

In [175]:
img = torch.randn(226, 226,3)

In [179]:
img.unsqueeze(3).shape

torch.Size([226, 226, 3, 1])

In [182]:
torch.squeeze(for_reshape, 1)

tensor([[0.6273, 0.7358, 0.4368, 0.3023],
        [0.7786, 0.1018, 0.8160, 0.3060],
        [0.5077, 0.4012, 0.5606, 0.3489]])

## Numpy and PyTorch

In [194]:
first = first.numpy()

In [187]:
type(first)

numpy.ndarray

In [192]:
first = torch.from_numpy(first)

In [193]:
type(first)

torch.Tensor