# NN Module

In [6]:
import torch
import torch.nn as nn
from torchinfo import summary

In [13]:
# create model class
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        # linear layer with one input that is number of feateurs and one output
        # self.linear1 = nn.Linear(num_features, 3)
        # self.relu = nn.ReLU()
        # self.linear2 = nn.Linear(3, 1)
        # self.sigmoid = nn.Sigmoid()

        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )

    def forward(self, features):
        
        out = self.network(features)
        
        return out
    



In [14]:
# create dateset
features = torch.rand(10,5)

# create model
model = Model(features.size(1))

# forward pass

model(features)


tensor([[0.4089],
        [0.4075],
        [0.4109],
        [0.4120],
        [0.4139],
        [0.4142],
        [0.4112],
        [0.4118],
        [0.4111],
        [0.4141]], grad_fn=<SigmoidBackward0>)

In [17]:
# show model weights
print(model.network[0].weight)
print(model.network[0].bias)

Parameter containing:
tensor([[-0.4041, -0.1928, -0.2711,  0.4130, -0.3176],
        [-0.1861, -0.1040,  0.3355,  0.2706, -0.3385],
        [ 0.3453,  0.1005, -0.1993,  0.3783, -0.0795]], requires_grad=True)
Parameter containing:
tensor([-0.1079, -0.0937,  0.2397], requires_grad=True)


In [16]:

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00